name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: travel-agency-448103
  REGION: us-central1
  SERVICE_NAME: travel-agency-service
  REPOSITORY: cloud-run-source-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    # Note: Service account needs these roles:
    # - Artifact Registry Administrator (roles/artifactregistry.admin)
    # - Cloud Run Admin (roles/run.admin)
    # - Storage Admin (roles/storage.admin)
    # - Service Account Token Creator (roles/iam.serviceAccountTokenCreator)

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Verify Authentication
        run: |
          echo "🔍 Verifying authentication..."
          gcloud auth list
          echo "📋 Current project settings:"
          gcloud config list project

      - name: Configure Docker for Artifact Registry
        run: |
          echo "🔧 Configuring Docker authentication..."
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build and Push Container
        run: |
          echo "📦 Building Docker image..."
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/app:${{ github.sha }} \
            --build-arg NODE_ENV=production .
          
          echo "⬆️ Pushing to Artifact Registry..."
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/app:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          echo "🚀 Deploying to Cloud Run..."
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/app:${{ github.sha }} \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --port 8080 \
            --memory 256Mi \
            --cpu 1 \
            --min-instances 0 \
            --max-instances 1 \
            --set-env-vars NODE_ENV=production

      - name: Show Service URL
        run: |
          echo "✨ Deployment complete!"
          echo "Service URL: $(gcloud run services describe ${{ env.SERVICE_NAME }} --region ${{ env.REGION }} --format 'value(status.url)')" 