name: Deploy to Cloud Run for Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3
      
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          project_id: travel-agency-448103
          install_components: 'gke-gcloud-auth-plugin'
      
      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
          
      - name: Create Artifact Registry repository
        run: |
          gcloud artifacts repositories create travel-agency-repo \
            --repository-format=docker \
            --location=us-central1 \
            --description="Travel Agency Docker repository" \
            --quiet || true
      
      - name: Build and push Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/travel-agency-448103/travel-agency-repo/travel-agency-app:${{ github.sha }} .
          docker push us-central1-docker.pkg.dev/travel-agency-448103/travel-agency-repo/travel-agency-app:${{ github.sha }}
      
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy travel-agency-app \
            --image us-central1-docker.pkg.dev/travel-agency-448103/travel-agency-repo/travel-agency-app:${{ github.sha }} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --set-env-vars NODE_ENV=production 