name: Deploy to Cloud Run for Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: travel-agency-448103
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      
      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          
      - name: Create Artifact Registry repository
        run: |
          gcloud artifacts repositories create travel-agency-repo \
            --repository-format=docker \
            --location=us-central1 \
            --description="Travel Agency Docker repository" || true
      
      - name: Build and push Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/travel-agency-448103/travel-agency-repo/travel-agency-app:${{ github.sha }} .
          docker push us-central1-docker.pkg.dev/travel-agency-448103/travel-agency-repo/travel-agency-app:${{ github.sha }}
      
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy travel-agency-app \
            --image us-central1-docker.pkg.dev/travel-agency-448103/travel-agency-repo/travel-agency-app:${{ github.sha }} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --set-env-vars NODE_ENV=production 