name: Deploy to Cloud Run for Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: travel-agency-448103
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      
      - name: Build and push Docker image
        run: |
          gcloud auth configure-docker
          docker build -t gcr.io/travel-agency-448103/travel-agency-app:${{ github.sha }} .
          docker push gcr.io/travel-agency-448103/travel-agency-app:${{ github.sha }}
      
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy travel-agency-app \
            --image gcr.io/travel-agency-448103/travel-agency-app:${{ github.sha }} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --set-env-vars NODE_ENV=production 